#!/bin/bash
#
# A template for creating command line scripts taking options, commands
# and arguments.
#
# Exit values:
#  0 on success
#  1 on failure
#



# Name of the script
SCRIPT=$( basename "$0" )

# Current version
VERSION="1.0.0"



#
# Message to display for usage and help.
#
function usage
{
    local txt=(
"Utility $SCRIPT for doing stuff."
"Usage: $SCRIPT [options] <command> [arguments]"
""
"Command:"
"  reverse [some text]          Reverse the text"
"  factors [any number] [any number] ...  Display primes of any given number('s)"
"
"""
"Options:"
"  --help, -h     Print help."
"  --version, -h  Print version."
"  reverse, -r  Reverse text."
"  factors, -f  Factors of a number."
    )
    
    printf "%s\n" "${txt[@]}"
}



#
# Message to display when bad usage.
#
function badUsage
{
    local message="$1"
    local txt=(
"For an overview of the command, execute:"
"$SCRIPT --help"
    )
    
    [[ $message ]] && printf "$message\n"

    printf "%s\n" "${txt[@]}"
}



#
# Message to display for version.
#
function version
{
    local txt=(
"$SCRIPT version $VERSION"
    )

    printf "%s\n" "${txt[@]}"
}



#
# Reverse. Function that display text in reverse.
#

function reverse
{
    local txt=(
""
    )
    echo "$*"|rev
}



#
# Reverse. Function that display text in reverse.
#

function factors
{
    local txt=(
""
    )
    kykla=$#
    kykla=$((kykla+1))

    sweet=1
    for z in "$@";do
        if [ $sweet -gt 1 ] && [ $sweet -lt $kykla ];then
            athj=""
            num=$z
            for (( i=2; i<=$z; i++ ));do
                while [ $((num%$i)) == 0 ];do
                    #echo $i
                    athj=$athj" $i"
                    #echo $athj
                    num=$((num/$i))
                done
            done
            echo $z":"$athj
        fi
        sweet=$((sweet+1))
    done
    
}



#
# Process options
#
while (( $# ))
do
    case "$1" in

        --help | -h)
            usage
            exit 0
        ;;

        --version | -v)
            version
            exit 0
        ;;

        reverse | -r)
            reverse "$2" "$3"
            exit 0
        ;;

        factors | -f)
            factors "$@"
            exit 0
        ;;
        
        *)
            badUsage "Option/command not recognized."
            exit 1
        ;;
        
    esac
done

badUsage
exit 1
